# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: docker-postgres
    environment:
      POSTGRES_DB: batch_spring
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - api_data:/var/lib/postgresql/data

volumes:
  api_data: