spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batch_spring
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect